server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: oauth2-server
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauthdb?useSSL=false
  #  driver-class-name: org.h2.Driver
  #  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  #  username: root
  #  password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true   
  #h2: 
  #  console:
  #    enabled: true
  #    path: /h2-console
  #    settings:
  #      trace: false
  #      web-allow-others: false
      